"""
remove obsolete index

Revision ID: 1cea171e16e0
Revises: bd46df2a146d
Create Date: 2026-07-29 14:12:39.855476
"""

from typing import Sequence, Union

from sqlalchemy import inspect

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cea171e16e0"
down_revision: Union[str, None] = "bd46df2a146d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    """
    執行資料庫增量升級 (Upgrade)。
    """
    globals().get("upgrade_%s" % engine_name, lambda: None)()


def downgrade(engine_name: str = "") -> None:
    """
    執行資料庫降級 (Downgrade)。
    """
    globals().get("downgrade_%s" % engine_name, lambda: None)()


def upgrade_crawler() -> None:
    """
    執行 Crawler 資料庫的升級操作 (移除不必要的索引)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = [idx["name"] for idx in inspector.get_indexes("external_links")]
    if "ix_external_links_job_status_ip" in indexes:
        with op.batch_alter_table("external_links", schema=None) as batch_op:
            batch_op.drop_index("ix_external_links_job_status_ip")

    # ### end Alembic commands ###


def downgrade_crawler() -> None:
    """
    執行 Crawler 資料庫的降級操作 (還原移除的索引)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_links", schema=None) as batch_op:
        batch_op.create_index(
            "ix_external_links_job_status_ip", ["job_id", "http_status_code", "ip_address"], unique=False
        )

    # ### end Alembic commands ###
