# pylint: skip-file
"""
初始資料庫 Schema 遷移腳本 (v1.9.7 基線模型)。

建立 Auth DB (users, invitations, sessions, password_reset_tokens, auth_logs)
與 Crawler DB (jobs, crawl_queue, external_links) 之完整表結構、外鍵與條件索引。

Revision ID: 2f5653065b96
Revises: None
Create Date: 2026-07-29 08:01:03.214503
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f5653065b96"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str = "") -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_auth() -> None:
    """
    執行資料庫增量升級 (Upgrade)。

    建立專案運作所需之所有 Auth DB 與 Crawler DB 表結構、外鍵與索引。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_logs", schema=None) as batch_op:
        batch_op.create_index("ix_auth_logs_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_auth_logs_user_id", ["user_id"], unique=False)

    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_invitations_token"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index("ix_invitations_user_id", ["user_id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("is_first_login", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sessions_user_id", ["user_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )


def upgrade_crawler() -> None:
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("start_url", sa.Text(), nullable=False),
        sa.Column("target_domains", sa.Text(), nullable=False),
        sa.Column("trusted_domains", sa.Text(), nullable=False),
        sa.Column("config_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("progress_stats", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "crawl_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("status_category", sa.String(length=30), nullable=False),
        sa.Column("is_secure", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crawl_queue", schema=None) as batch_op:
        batch_op.create_index(
            "ix_crawl_queue_internal_issues",
            ["job_id"],
            unique=False,
            postgresql_where=sa.text("status IN ('failed', 'warning') OR is_secure = false"),
            sqlite_where=sa.text("status IN ('failed', 'warning') OR is_secure = 0"),
        )
        batch_op.create_index("ix_crawl_queue_job_category", ["job_id", "status_category"], unique=False)
        batch_op.create_index("ix_crawl_queue_job_status_id", ["job_id", "status", "id"], unique=False)
        batch_op.create_index("ix_crawl_queue_job_url", ["job_id", "url"], unique=False)

    op.create_table(
        "external_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("target_domain", sa.String(length=255), server_default="", nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("is_secure", sa.Boolean(), nullable=False),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("status_category", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "source_url", "target_url", name="uq_external_links_job_src_tgt"),
    )
    with op.batch_alter_table("external_links", schema=None) as batch_op:
        batch_op.create_index("ix_external_links_job_category", ["job_id", "status_category"], unique=False)
        batch_op.create_index("ix_external_links_job_created", ["job_id", "created_at"], unique=False)
        batch_op.create_index("ix_external_links_job_domain", ["job_id", "target_domain"], unique=False)
        batch_op.create_index("ix_external_links_job_target", ["job_id", "target_url"], unique=False)

    # ### end Alembic commands ###


def downgrade_crawler() -> None:
    """
    執行資料庫降級 (Downgrade)。

    刪除升級時建立之所有 Auth DB 與 Crawler DB 表結構與索引。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_links", schema=None) as batch_op:
        batch_op.drop_index("ix_external_links_job_target")
        batch_op.drop_index("ix_external_links_job_domain")
        batch_op.drop_index("ix_external_links_job_created")
        batch_op.drop_index("ix_external_links_job_category")

    op.drop_table("external_links")
    with op.batch_alter_table("crawl_queue", schema=None) as batch_op:
        batch_op.drop_index("ix_crawl_queue_job_url")
        batch_op.drop_index("ix_crawl_queue_job_status_id")
        batch_op.drop_index("ix_crawl_queue_job_category")
        batch_op.drop_index(
            "ix_crawl_queue_internal_issues",
            postgresql_where=sa.text("status IN ('failed', 'warning') OR is_secure = false"),
            sqlite_where=sa.text("status IN ('failed', 'warning') OR is_secure = 0"),
        )

    op.drop_table("crawl_queue")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_user_id"))

    op.drop_table("jobs")


def downgrade_auth() -> None:
    op.drop_table("users")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_user_id")

    op.drop_table("sessions")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index("ix_invitations_user_id")

    op.drop_table("invitations")
    with op.batch_alter_table("auth_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_logs_user_id")
        batch_op.drop_index("ix_auth_logs_created_at")

    op.drop_table("auth_logs")
    # ### end Alembic commands ###
