# pylint: skip-file
"""
Add check constraint for job status

Revision ID: bd46df2a146d
Revises: 2f5653065b96
Create Date: 2026-07-29 13:38:18.680649
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bd46df2a146d"
down_revision: Union[str, None] = "2f5653065b96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    執行資料庫增量升級 (Upgrade)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import op
    with op.batch_alter_table('jobs') as batch_op:
        batch_op.create_check_constraint(
            "job_status_check",
            condition="status IN ('pending', 'queued', 'starting', 'running', 'paused', 'completed', 'error')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    執行資料庫降級 (Downgrade)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import op
    with op.batch_alter_table('jobs') as batch_op:
        batch_op.drop_constraint("job_status_check", type_="check")
    # ### end Alembic commands ###
