"""
Add check constraint for job status

Revision ID: bd46df2a146d
Revises: 2f5653065b96
Create Date: 2026-07-29 13:38:18.680649
"""

# pylint: disable=no-member, invalid-name
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd46df2a146d"
down_revision: Union[str, None] = "2f5653065b96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    """
    依據指定的引擎名稱，執行對應的資料庫升級操作。

    Args:
        engine_name (str): 資料庫引擎名稱 ("auth" 或 "crawler")。預設為空字串。
    """
    globals().get(f"upgrade_{engine_name}", lambda: None)()


def downgrade(engine_name: str = "") -> None:
    """
    依據指定的引擎名稱，執行對應的資料庫降級操作。

    Args:
        engine_name (str): 資料庫引擎名稱 ("auth" 或 "crawler")。預設為空字串。
    """
    globals().get(f"downgrade_{engine_name}", lambda: None)()


def upgrade_crawler() -> None:
    """
    執行 Crawler 資料庫的升級操作 (新增狀態檢查約束)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.create_check_constraint(
            "job_status_check",
            condition="status IN ('pending', 'queued', 'starting', 'running', 'paused', 'completed', 'error')",
        )
    # ### end Alembic commands ###


def downgrade_crawler() -> None:
    """
    執行 Crawler 資料庫的降級操作 (移除狀態檢查約束)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.drop_constraint("job_status_check", type_="check")
    # ### end Alembic commands ###
