"""
add_job_diff_tables

Revision ID: e7e125f3ee58
Revises: 1cea171e16e0
Create Date: 2026-07-31 14:25:00.121593

"""

# pylint: disable=no-member, invalid-name
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7e125f3ee58"
down_revision: Union[str, None] = "1cea171e16e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str = "") -> None:
    """
    依據指定的引擎名稱，執行對應的資料庫升級操作。

    Args:
        engine_name (str): 資料庫引擎名稱 ("auth" 或 "crawler")。預設為空字串。
    """
    globals().get(f"upgrade_{engine_name}", lambda: None)()


def downgrade(engine_name: str = "") -> None:
    """
    依據指定的引擎名稱，執行對應的資料庫降級操作。

    Args:
        engine_name (str): 資料庫引擎名稱 ("auth" 或 "crawler")。預設為空字串。
    """
    globals().get(f"downgrade_{engine_name}", lambda: None)()


def upgrade_crawler() -> None:
    """
    執行 Crawler 資料庫的升級操作 (新增 job_diff_results 與 job_diff_items 資料表)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_diff_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_a_id", sa.String(length=36), nullable=False),
        sa.Column("job_b_id", sa.String(length=36), nullable=False),
        sa.Column("summary_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["job_a_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_b_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_a_id", "job_b_id", name="uq_job_diff_a_b"),
    )
    op.create_index("ix_job_diff_last_accessed", "job_diff_results", ["last_accessed_at"], unique=False)

    op.create_table(
        "job_diff_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("diff_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["diff_id"], ["job_diff_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_diff_items_diff_category", "job_diff_items", ["diff_id", "category"], unique=False)
    # ### end Alembic commands ###


def downgrade_crawler() -> None:
    """
    執行 Crawler 資料庫的降級操作 (移除 job_diff_results 與 job_diff_items 資料表)。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_diff_items_diff_category", table_name="job_diff_items")
    op.drop_table("job_diff_items")
    op.drop_index("ix_job_diff_last_accessed", table_name="job_diff_results")
    op.drop_table("job_diff_results")
    # ### end Alembic commands ###
